-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 18:55:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema studentsdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema studentsdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `studentsdb` DEFAULT CHARACTER SET utf8 ;
USE `studentsdb` ;

-- -----------------------------------------------------
-- Table `studentsdb`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentsdb`.`subject` (
  `idSubject` INT(11) NOT NULL AUTO_INCREMENT,
  `subjectName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSubject`),
  UNIQUE INDEX `idsubject_UNIQUE` (`idSubject` ASC))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studentsdb`.`controlwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentsdb`.`controlwork` (
  `idcontrolWork` INT(11) NOT NULL AUTO_INCREMENT,
  `subject_idSubject` INT(11) NOT NULL,
  `controlName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcontrolWork`),
  UNIQUE INDEX `idcontrolWork_UNIQUE` (`idcontrolWork` ASC),
  INDEX `fk_controlWork_subject1_idx` (`subject_idSubject` ASC),
  CONSTRAINT `fk_controlWork_subject1`
  FOREIGN KEY (`subject_idSubject`)
  REFERENCES `studentsdb`.`subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studentsdb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentsdb`.`course` (
  `idCourse` INT(11) NOT NULL AUTO_INCREMENT,
  `courseNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCourse`),
  UNIQUE INDEX `idCourse_UNIQUE` (`idCourse` ASC))
  ENGINE = InnoDB
  AUTO_INCREMENT = 4
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studentsdb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentsdb`.`group` (
  `idGroup` INT(11) NOT NULL AUTO_INCREMENT,
  `groupName` VARCHAR(45) NOT NULL,
  `course_idCourse` INT(11) NOT NULL,
  PRIMARY KEY (`idGroup`),
  UNIQUE INDEX `idGroup_UNIQUE` (`idGroup` ASC),
  INDEX `fk_group_course1_idx` (`course_idCourse` ASC),
  CONSTRAINT `fk_group_course1`
  FOREIGN KEY (`course_idCourse`)
  REFERENCES `studentsdb`.`course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  AUTO_INCREMENT = 4
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studentsdb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentsdb`.`student` (
  `idstudent` INT(11) NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `group_idGroup` INT(11) NOT NULL,
  PRIMARY KEY (`idstudent`),
  UNIQUE INDEX `idstudent_UNIQUE` (`idstudent` ASC),
  INDEX `fk_student_group1_idx` (`group_idGroup` ASC),
  CONSTRAINT `fk_student_group1`
  FOREIGN KEY (`group_idGroup`)
  REFERENCES `studentsdb`.`group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studentsdb`.`assesment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentsdb`.`assesment` (
  `controlWork_idcontrolWork` INT(11) NOT NULL,
  `student_idstudent` INT(11) NOT NULL,
  `mark` VARCHAR(45) NOT NULL,
  `idMark` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idMark`),
  UNIQUE INDEX `idMark_UNIQUE` (`idMark` ASC),
  INDEX `fk_controlWork_has_student_student1_idx` (`student_idstudent` ASC),
  INDEX `fk_controlWork_has_student_controlWork1_idx` (`controlWork_idcontrolWork` ASC),
  CONSTRAINT `fk_controlWork_has_student_controlWork1`
  FOREIGN KEY (`controlWork_idcontrolWork`)
  REFERENCES `studentsdb`.`controlwork` (`idcontrolWork`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_controlWork_has_student_student1`
  FOREIGN KEY (`student_idstudent`)
  REFERENCES `studentsdb`.`student` (`idstudent`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studentsdb`.`subject_has_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `studentsdb`.`subject_has_student` (
  `subject_idSubject` INT(11) NOT NULL,
  `student_idstudent` INT(11) NOT NULL,
  PRIMARY KEY (`subject_idSubject`, `student_idstudent`),
  INDEX `fk_subject_has_student_student1_idx` (`student_idstudent` ASC),
  INDEX `fk_subject_has_student_subject1_idx` (`subject_idSubject` ASC),
  CONSTRAINT `fk_subject_has_student_student1`
  FOREIGN KEY (`student_idstudent`)
  REFERENCES `studentsdb`.`student` (`idstudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subject_has_student_subject1`
  FOREIGN KEY (`subject_idSubject`)
  REFERENCES `studentsdb`.`subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
